config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # 'controller#action'
  root "pages#home"

  # The priority is based on the order of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # route /about goes to controller pages_controller and calls the about method.
  get "about", to: "pages#about"

  # Add the routes index, create, new, edit, show, update and destroy. --rake routes-- to see.
  resources :articles

  # route /signup goes to controller users_controller and calls the new method.
  get "signup", to: "users#new"

  # Add the routes index, create, edit, show, update and destroy. all the normal routes resources provides except new.
  resources :users, except: [:new]

  # route /login goes to controller sessions_controller and calls the new method.
  get "login", to: "sessions#new"

  # route /login goes to controller sessions_controller and calls the create method when you attempt to create a user on that page/route.
  post "login", to: "sessions#create"

  # route /logout goes to controller sessions_controller and calls the destroy method.
  delete "logout", to: "sessions#destroy"

  # Add the routes index, create, edit, show, update and new . all the normal routes resources provides except destroy.
  resources :categories, except: [:destroy]
end

app/models/article.rb
class Article < ActiveRecord::Base
  # This record belongs_to only one user. The user has many articles.
  belongs_to :user
  # We want the article to have many categories. So we need to do this through an association.
  # A article has many article_categories model/table.
  has_many :article_categories
  # And a article has many categories through the article_categories model/table.
  # This allows us to have associations with another table through a table article_categories
  has_many :categories, through: :article_categories

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # This calls this method :set_article before the action is called. and only in the specified actions. To prevent redundance and set the article in each method that needs it.
  before_action :set_article, only: [:edit, :update, :show, :destroy]

  # Before any other action call the require_user method from the application_controller.
  # This will require the a user to be logged in for every action except index and show.
  before_action :require_user, except: [:index, :show]

  # Before any other action require the same user for only edit, update and destroy.
  # We only want the user that created this record to be able to edit or update or destroy it.
  before_action :require_same_user, only: [:edit, :update, :destroy]

  # The index of a particular table is usually the page to list out all of the records.
  def index
    # Assigns all article records to the @articles instance variables.
    # @articles = Article.paginate(page: params[:page])
    # Adds pagination to all articles using the gem 'will_paginate', '3.1.5' gem 'bootstrap-will_paginate', '1.0.0'
    @articles = Article.paginate(page: params[:page], per_page: 4)
  end

  # @ specifies an instance varible.
  # @ here it is being set to a new Article object.
  def new
    @article = Article.new
  end

  # Looking at rake routes you will find the edit page is displayed /articles/:id/edit
  # We need to set the @article instance to a specific id to be able to edit a particular record.
  def edit
  end

  def create
    # render plain: params[:article].inspect
    # @article.save
    # redirect_to articles_path(@article)

    # Creates a new Article object
    @article = Article.new(article_params)

    # @article.user = User.first
    # Can now set it to the current user because we have that method available and are requiring a user to create.
    @article.user = current_user

    # Handles if Articles saves or not based on the validations on the model.
    if @article.save
      # If article saves then redirect to the article with a message.
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      # If article does not save the re render the new article page. Errors displayed and handled on the new.html.erb
      render :new
    end
  end

  # This is the page that handles the submission of the edit/update method/page.
  def update
    # If the record successfully updates the notify and send back to the article page with the updated info.
    # We need to update something so we again need to white list the information with the article_params method like we did when creating.
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated."
      redirect_to article_path(@article)

    # Else go back to the edit page.
    else
      render :edit
    end
  end

  # this handles the submission of a new article.
  def show
  end

  # This handles the delete ability of the app.
  def destroy
    # Deletes the record.
    @article.destroy
    flash[:danger] = "Article was successfully deleted."

    # Sends you back to the main list of articles.
    redirect_to articles_path
  end

  private

  def set_article
    # Set the @article variable instance to the specific record based on the id.
    @article = Article.find(params[:id])
  end

  def article_params
    # params.requires(:toplevelkey).permit(:secondlevelone, :secondleveltwo)
    # We are white listing these parameters.
    # We need to passin/whitelist the category_ids...
    # that are associated with the article from the category table.
    # This info is like recieving a json or xml object and being able to change the info.
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    # if there is a current user(this method is from application_controller) and it is not the user for the article and not an admin...
    if (current_user != @article.user) && !current_user.admin?
      # Then flash danger message to the user.
      flash[:danger] = "This is not your article."
      # Then redirect to the home page.
      redirect_to root_path
    end
  end
end

app/views/articles/_article.html.erb
<%# Set this partial to a standard variable that any view can user ie: obj %>
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
        <!-- To edit or view a specific record you need to pass in the article. -->
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <p><%= truncate(article.description, length: 60) %></p>
          <div class="article-meta-details">
            <%# time_ago_in_words is a ruby method for displaying dates. %>
            <p>
              <small>Created By: <%= article.user.username if article.user %>,
                    <%= time_ago_in_words(article.created_at) %> ago,
                    Last Updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
            </p>
          </div>
        </div>
        <% if article.categories.any? %>
          <p>Categories: <%= render article.categories %></p>
        <% end %>
        <%# If user is logged_in and the current_user logged_in is equal to the user that created the article or is an admin user then display the actions below. %>
        <% if logged_in? && current_user == article.user || current_user.try(:admin?) %>
          <div class="article-actions">
            <%# you must pass in the article to edit or delete. %>
            <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
            <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete article" }, class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>

      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%# Setting the obj to @article for errors %>
<%= render "shared/errors", obj: @article %>
<div class="row">
  <div class="col-xs-12">
    <%# passing in the article to create a form %>
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |form| %>
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= form.label :title %>
        </div>
        <div class="col-sm-8">
          <%= form.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= form.label :description %>
        </div>
        <div class="col-sm-8">
          <%= form.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col-sm-offset-2 col-sm-8">
            <%# We are creating a collection of check boxes of categories using singular_ids method...
            For the Category.all Collection using id as the value method...
            and name as the text method... %>
            <%= form.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <%# Here we are creating a label with a checkbox inside of it with the specified classes.
              We are adding the text value of the :name of the Category. %>
              <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= form.submit class: "btn btn-primary btn-lg" %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-offset-4 col-xs-4">
      [ <%= link_to "Cancel and return to articles", articles_path %> ]
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit Article</h1>

<%= render "form" %>

app/views/articles/index.html.erb
<h1 align="center">All Articles</h1>

<div align="center">
  <%= will_paginate %>
</div>
<%# Set the varible to your database records that you want to interate. %>
<%= render 'article', obj: @articles %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create an Article</h1>

<%= render "form" %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>

<div class="well col-xs-8 col-xs-offset-2">
  <%# If the article has a author/user then display the author/user info for the article %>
  <% if @article.user %>
    <ul class="listing">
      <div class="row text-center">
        <div class="col-md-4 col-md-offset-4">
          <li>Created by:</li>
          <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
          <li class="article-title"><%= link_to @article.user.username, user_path(@article.user) %></li>
          <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
        </div>
      </div>
    </ul>
  <% end %>
  <h4 class="text-center description"><strong>Description:</strong></h4>
  <hr>
  <!-- simple_format displays the formating that you made in the text editor -->
  <p><%= simple_format(@article.description) %></p>
  <% if @article.categories.any? %>
    <%# We will now interate and print each category %>
    <%# This render article categories will have almost the same effect as a .each %>
    <p>Categories: <%= render @article.categories %></p>
  <% end %>
  <div class="article-actions">

    <%# If user is logged_in and the current_user logged_in is equal to the user that created the article then display the actions below. %>
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
      <%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
      <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete article" }, class: "btn btn-xs btn-danger" %>
    <% end %>

    <%= link_to "View Articles", articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>