config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # 'controller#action'
  root "pages#home"

  # The priority is based on the order of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # route /about goes to controller pages_controller and calls the about method.
  get "about", to: "pages#about"

  # Add the routes index, create, new, edit, show, update and destroy. --rake routes-- to see.
  resources :articles

  # route /signup goes to controller users_controller and calls the new method.
  get "signup", to: "users#new"

  # Add the routes index, create, edit, show, update and destroy. all the normal routes resources provides except new.
  resources :users, except: [:new]

  # route /login goes to controller sessions_controller and calls the new method.
  get "login", to: "sessions#new"

  # route /login goes to controller sessions_controller and calls the create method when you attempt to create a user on that page/route.
  post "login", to: "sessions#create"

  # route /logout goes to controller sessions_controller and calls the destroy method.
  delete "logout", to: "sessions#destroy"

  # Add the routes index, create, edit, show, update and new . all the normal routes resources provides except destroy.
  resources :categories, except: [:destroy]
end

app/models/category.rb
class Category < ActiveRecord::Base
  # We want a category to have many articles. We need to do this through an association from another table.
  # A category has_many article_categories
  has_many :article_categories
  # A category has_many articles through the article_categories model/table association.
  has_many :articles, through: :article_categories
  # name field must be present, unique, and with min & max rules.
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  # Validates whether the value of the specified attributes are unique across the system.
  # Useful for making sure that only one field can be named a certain way. In this case :name.
  validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 4)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category Created."
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category updated."
      redirect_to category_path(@category)
    else
      render "edit"
    end
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 4)
  end

  private

  def require_admin
    # if user is not logged in or not logged in and the current_user is not an admin...
    if !logged_in? || (logged_in? && !current_user.admin?)
      # Then flash message and redirect.
      flash[:danger] = "Only admins can perform action."
      redirect_to categories_path
    end
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %> &nbsp;</span>

app/views/categories/_form.html.erb
<%= render "shared/errors", obj: @category %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |form| %>
  <div class="form-group">
    <div class="col-sm-2 control-label">
      <%= form.label :name %>
    </div>
    <div class="col-sm-8">
      <%= form.text_field :name, class: "form-control", placeholder: "Category Name.", autofocus: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= form.submit class: "btn btn-primary btn-lg" %>
    </div>
  </div>
<% end %>
<div class="col-xs-offset-4 col-xs-4">
  [ <%= link_to "Cancel and return to articles", articles_path %> ]
</div>

app/views/categories/edit.html.erb
<h1 align="center">Edit Category</h1>

<%= render "form" %>

app/views/categories/index.html.erb
<h1 align="center">All Categories</h1>
<div align="center">
  <%= will_paginate %>
  <% @categories.each do |category| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li class="article-title">
            <%= link_to "#{category.name}", category_path(category) %>
          </li>
          <li><small><%= pluralize(category.articles.count, "article") %></small></li>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 align="center">Create Category</h1>

<%= render "form" %>

app/views/categories/show.html.erb
<h1 align="center"><%= "Category: " + @category.name %></h1>

<%# This will_paginate the articles based on the method specified in the index method of the articles controller. %>
<%# The methods used to paginate come from gem 'will_paginate', '~> 3.1', '>= 3.1.6' gem 'bootstrap-will_paginate', '1.0.0' %>
<div align="center">
  <% if logged_in? and current_user.admin? %>
    <div class="row" style="margin-bottom: 30px;">
      <span class="badge"><%= link_to "Edit Category Name", edit_category_path(@category) %></span>
    </div>
  <% end %>
  <%= will_paginate @category_articles %>
</div>

<%# Set the varible to your database records that you want to interate. %>
<%# Then renders our partial app/views/articles/_article.html.erb %>
<%= render 'articles/article', obj: @category_articles %>

<div align="center">
  <%= will_paginate @category_articles %>
</div>