config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # 'controller#action'
  root "pages#home"

  # The priority is based on the order of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # route /about goes to controller pages_controller and calls the about method.
  get "about", to: "pages#about"

  # Add the routes index, create, new, edit, show, update and destroy. --rake routes-- to see.
  resources :articles

  # route /signup goes to controller users_controller and calls the new method.
  get "signup", to: "users#new"

  # Add the routes index, create, edit, show, update and destroy. all the normal routes resources provides except new.
  resources :users, except: [:new]

  # route /login goes to controller sessions_controller and calls the new method.
  get "login", to: "sessions#new"

  # route /login goes to controller sessions_controller and calls the create method when you attempt to create a user on that page/route.
  post "login", to: "sessions#create"

  # route /logout goes to controller sessions_controller and calls the destroy method.
  delete "logout", to: "sessions#destroy"

  # Add the routes index, create, edit, show, update and new . all the normal routes resources provides except destroy.
  resources :categories, except: [:destroy]
end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer mt-5">
    <small>Copyright &copy; <%= link_to "Alpha Blog", "#" %> | <%= link_to "Rob Berryhill", "#" %></small>
    <nav>
      <ul>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <!-- Ruby helper to create a div tage with msg as content and an id and string validation. -->
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Users", users_path %></li>

        <%# If user is logged_in then display these actions. %>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "New Article", new_article_path %></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Categories", categories_path %></li>
            <%# We grabbing all categories in the table and listing each of them. %>
            <% Category.all.each do |category| %>
              <%# Then we are linking them with their name and by the specific path of the particular category. %>
              <li><%= link_to "#{category.name}", category_path(category) %></li>
            <% end %>
            <%# If user is logged_in and the current_user is an admin then give access to this link %>
            <% if logged_in? and current_user.admin? %>
              <li role="separator" class="divider"></li>
              <li><%= link_to "New Category", new_category_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>

      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

      <ul class="nav navbar-nav navbar-right">

        <%# If user is logged_in then display these account links. %>
        <% if logged_in? %>
          <li><%= link_to "Log Out", logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= "Admin " if current_user.admin? %>Profile <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
              <li><%= link_to "View Profile", user_path(current_user) %></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>

        <%# If not logged_in then display links to login or signup %>
        <% else %>
          <li><%= link_to "Log In", login_path %></li>
          <li><%= link_to "Sign Up", signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navigation"%>
    <%= render "layouts/messages" %>
    <div class="container">
        <%= yield %>
    </div>
    <%= render "layouts/footer"%>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>